# -*- coding: utf-8 -*-
"""Te damos la bienvenida a Colaboratory

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb

Taller en clase, Realizar clase estudiante con objetos y atributos, la cedula solo tiene valores numericos y a 10 digitos y el semestre solo permite del 1 al 9
"""

class Estudiante:
    """Clase que representa a un estudiante con validaciones estrictas."""

    def __init__(self, nombre, apellido, cedula, email, semestre):
        self.nombre = nombre
        self.apellido = apellido
        # Los siguientes activan los setters para validación inicial
        self.cedula = cedula
        self.email = email
        self.semestre = semestre
        self.__materias = []  # Atributo privado

    # --- Propiedad: Cédula (Encapsulada) ---
    @property
    def cedula(self):
        return self.__cedula

    @cedula.setter
    def cedula(self, valor):
        if isinstance(valor, str) and valor.isdigit() and len(valor) == 10:
            self.__cedula = valor
        else:
            raise ValueError("Error: La cédula debe tener 10 dígitos numéricos.")

    # --- Propiedad: Semestre (Encapsulada) ---
    @property
    def semestre(self):
        return self.__semestre

    @semestre.setter
    def semestre(self, valor):
        if isinstance(valor, int) and 1 <= valor <= 9:
            self.__semestre = valor
        else:
            raise ValueError("Error: El semestre debe ser un entero entre 1 y 9.")

    # --- Gestión de Materias (Lógica de Negocio) ---
    @property
    def materias(self):
        """Retorna una copia de la lista para proteger la original."""
        return self.__materias.copy()

    def agregar_materia(self, materia):
        """Método público para modificar el atributo privado __materias."""
        if materia and isinstance(materia, str):
            self.__materias.append(materia.strip())

    def __str__(self):
        """Representación formal del objeto siguiendo PEP 8."""
        return (f"Estudiante: {self.nombre} {self.apellido} | "
                f"ID: {self.cedula} | Semestre: {self.semestre}")


# --- Bloque de ejecución ---
if __name__ == "__main__":
    try:
        # Instanciación correcta
        estudiante_uno = Estudiante(
            "Luis", "Ramírez", "0987654321", "luis@correo.com", 4
        )
        estudiante_uno.agregar_materia("Cálculo Integral")

        print(estudiante_uno)
        print(f"Materias inscritas: {estudiante_uno.materias}")

        # Intento de acceso directo al atributo privado (lanzará error si se intenta)
        # print(estudiante_uno.__cedula)  # Esto daría AttributeError

    except ValueError as e:
        print(f"Validación fallida: {e}")